/*
 * model.h - the trained classifier, generated by tools/export_tree.py
 *
 * DO NOT EDIT BY HAND. Re-run the exporter instead:
 *     py -3 tools/export_tree.py
 *
 * Model:      DecisionTreeClassifier(max_depth=6, random_state=0)
 * Trained on: sessions 1 and 2, 195 windows
 * Held out:   session 3, 104 windows
 * Held-out accuracy: 0.865
 * Depth 4, 5 leaves, 3 of 8 features used
 *
 * Thresholds are in raw units - millimetres of deviation from the saved
 * distance reference, and ADC counts of deviation from the saved light
 * reference. The z-scoring used during training has been folded into the
 * constants, so no scaler is needed on the device.
 */
#ifndef MODEL_H
#define MODEL_H

// Window statistics over the last WINDOW samples, in raw units.
struct Features {
  float d_dist_mm_mean;
  float d_dist_mm_std;
  float d_dist_mm_min;
  float d_dist_mm_max;
  float d_ldr_mean;
  float d_ldr_std;
  float d_ldr_min;
  float d_ldr_max;
};

const int MODEL_WINDOW = 10;
const int MODEL_STRIDE = 5;

// 0 optimal  1 too_close  2 too_far  3 underlit  4 overlit
inline int classify(const Features &f) {
    if (f.d_dist_mm_mean <= -51.80f) {
      return 1;  // too_close
    } else {
      if (f.d_ldr_min <= -137.50f) {
        return 3;  // underlit
      } else {
        if (f.d_ldr_min <= 141.50f) {
          if (f.d_dist_mm_min <= 150.00f) {
            return 0;  // optimal
          } else {
            return 2;  // too_far
          }
        } else {
          return 4;  // overlit
        }
      }
    }
}

inline const char *className(int c) {
  switch (c) {
    case 0: return "OPTIMAL";
    case 1: return "TOO_CLOSE";
    case 2: return "TOO_FAR";
    case 3: return "UNDERLIT";
    case 4: return "OVERLIT";
    default: return "?";
  }
}

#endif
