"""
LightGuide Edge - export the winning decision tree as C
COM683 CW2 | Vishnu Vekariya B00969091 | Ulster University

    py -3 tools/export_tree.py

Reads the same captures, builds the same windows and fits the same tree as
tools/train_offline.py with seed 0, then writes firmware/03_inference/model.h.

Two things worth defending in the viva:

* The header is GENERATED, never hand-typed. Copying thresholds out of a printed
  tree by hand is how a model and its deployment quietly diverge; regenerating
  from the trained object means the firmware cannot disagree with the reported
  accuracy.
* The thresholds are written back in RAW UNITS (mm and ADC counts). The tree was
  fitted on z-scored features, but a threshold at z can be expressed as
  mean + z*std, so the standardisation is folded into the constants at export
  time. The firmware therefore needs no scaler, no floats to store, and no risk
  of the scaler and the model going out of step - it just compares millimetres to
  millimetres.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

sys.path.insert(0, str(Path(__file__).resolve().parent))
from train_offline import (CHANNELS, CLASS_NAMES, STRIDE, WINDOW,  # noqa: E402
                           clean, load_raw, window_features)

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "firmware" / "03_inference" / "model.h"
TEST_SESSION = 3


def emit_node(t, node, scaler, feat_names, depth, lines) -> None:
    pad = "  " * (depth + 2)
    if t.children_left[node] == t.children_right[node]:      # leaf
        cls = int(np.argmax(t.value[node][0]))
        lines.append(f"{pad}return {cls};  // {CLASS_NAMES[cls]}")
        return

    f = t.feature[node]
    z = t.threshold[node]
    raw = scaler.mean_[f] + z * scaler.scale_[f]             # fold the z-score away
    name = feat_names[f]

    lines.append(f"{pad}if (f.{name} <= {raw:.2f}f) {{")
    emit_node(t, t.children_left[node], scaler, feat_names, depth + 1, lines)
    lines.append(f"{pad}}} else {{")
    emit_node(t, t.children_right[node], scaler, feat_names, depth + 1, lines)
    lines.append(f"{pad}}}")


def main() -> None:
    df = clean(load_raw())
    X, y, groups, sessions, feat_names = window_features(df, CHANNELS)

    train = sessions != TEST_SESSION
    scaler = StandardScaler().fit(X[train])
    tree = DecisionTreeClassifier(max_depth=6, random_state=0)
    tree.fit(scaler.transform(X[train]), y[train])

    acc = (tree.predict(scaler.transform(X[~train])) == y[~train]).mean()
    used = sorted({feat_names[f] for f in tree.tree_.feature if f >= 0})

    body: list[str] = []
    emit_node(tree.tree_, 0, scaler, feat_names, 0, body)

    lines = [
        "/*",
        " * model.h - the trained classifier, generated by tools/export_tree.py",
        " *",
        " * DO NOT EDIT BY HAND. Re-run the exporter instead:",
        " *     py -3 tools/export_tree.py",
        " *",
        f" * Model:      DecisionTreeClassifier(max_depth=6, random_state=0)",
        f" * Trained on: sessions 1 and 2, {int(train.sum())} windows",
        f" * Held out:   session {TEST_SESSION}, {int((~train).sum())} windows",
        f" * Held-out accuracy: {acc:.3f}",
        f" * Depth {tree.get_depth()}, {tree.get_n_leaves()} leaves, "
        f"{len(used)} of {len(feat_names)} features used",
        " *",
        " * Thresholds are in raw units - millimetres of deviation from the saved",
        " * distance reference, and ADC counts of deviation from the saved light",
        " * reference. The z-scoring used during training has been folded into the",
        " * constants, so no scaler is needed on the device.",
        " */",
        "#ifndef MODEL_H",
        "#define MODEL_H",
        "",
        "// Window statistics over the last WINDOW samples, in raw units.",
        "struct Features {",
        "  float d_dist_mm_mean;",
        "  float d_dist_mm_std;",
        "  float d_dist_mm_min;",
        "  float d_dist_mm_max;",
        "  float d_ldr_mean;",
        "  float d_ldr_std;",
        "  float d_ldr_min;",
        "  float d_ldr_max;",
        "};",
        "",
        f"const int MODEL_WINDOW = {WINDOW};",
        f"const int MODEL_STRIDE = {STRIDE};",
        "",
        "// 0 optimal  1 too_close  2 too_far  3 underlit  4 overlit",
        "inline int classify(const Features &f) {",
    ]
    lines += body
    lines += [
        "}",
        "",
        "inline const char *className(int c) {",
        "  switch (c) {",
    ]
    for i, n in enumerate(CLASS_NAMES):
        lines.append(f'    case {i}: return "{n.upper()}";')
    lines += [
        '    default: return "?";',
        "  }",
        "}",
        "",
        "#endif",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"held-out accuracy {acc:.3f}, depth {tree.get_depth()}, "
          f"{tree.get_n_leaves()} leaves")
    print(f"features used: {', '.join(used)}")
    print(f"written: {OUT}")


if __name__ == "__main__":
    main()
