"""
LightGuide Edge - Blackboard submission packaging
COM683 CW2 | Vishnu Vekariya | Ulster University

Builds the two zip components that are files (D1 Code, D2 Dataset). D3 Slides and D4 Video
are produced by hand and submitted separately - D4 goes to the Panopto Media Assignment
dropbox, not the normal file dropbox (docs/00-REQUIREMENTS-LOCKED.md section 2).

    py -3 tools/package_submission.py --ei-url https://studio.edgeimpulse.com/public/XXXX/live

Naming follows the handbook: SurnameFirstnameBNumber_Component.

    deliverables/VekariyaVishnuB00969091_Code.zip
    deliverables/VekariyaVishnuB00969091_Dataset.zip

Every zip is re-opened and listed after writing. The handbook is explicit that a corrupted
file is treated as a non-submission, so "it wrote without an exception" is not good enough -
the check has to actually read the archive back.
"""

from __future__ import annotations

import argparse
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DELIV = ROOT / "deliverables"

SURNAME, FIRSTNAME, BNUMBER = "Vekariya", "Vishnu", "B00969091"
STEM = f"{SURNAME}{FIRSTNAME}{BNUMBER}"

CODE_README = """LightGuide Edge - CW2 Code submission
COM683 Edge & Embedded Intelligence | {first} {sur} | {bno}
Ulster University

EDGE IMPULSE PROJECT (public)
-----------------------------
{ei}

WHAT IS IN HERE
---------------
firmware/            Arduino sketches. 03_inference is THE product - sense, classify,
                     guide, entirely on-device. Everything else is a diagnostic or a
                     step in producing the model. See RUN.md for which is which.
tools/               Python: calibration, labelled capture, dataset quality gate,
                     offline model comparison, online evaluation, figures, packaging.
docs/                Requirements, hardware, data protocol, ML plan, evaluation plan,
                     ethics/SDG, references, Q&A pack.
reports/             Generated evidence: gate results, offline and online results,
                     figures used in the deck.
models/              Trained artefacts and the frozen scaler constants.
data/processed/      The windowed feature table the offline models were trained on.

Raw captures are in the Dataset component, not here, to keep this archive small.

THE DEPLOYED MODEL
------------------
firmware/03_inference/model.h - a depth-4 decision tree, generated by
tools/export_tree.py and NOT hand-edited. The z-scoring applied during training is
folded into the constants, so the device needs no scaler at run time.

HOW TO BUILD
------------
arduino-cli compile --fqbn arduino:mbed_nano:nano33ble firmware/03_inference
arduino-cli upload -p COM4 --fqbn arduino:mbed_nano:nano33ble firmware/03_inference

Measured footprint: {footprint}
"""

DATASET_README = """LightGuide Edge - CW2 Dataset submission
COM683 Edge & Embedded Intelligence | {first} {sur} | {bno}

CONTENTS
--------
raw/            45 labelled capture files, 1,832 samples, ~8 Hz.
                Filename encodes session, label and timestamp.
                Each file opens with a `#` line carrying that session's reference
                setup, so every file is self-describing.
processed/      train.csv (195 windows, sessions 1-2)
                test.csv  (104 windows, session 3, held out)
edge_impulse/   The same data in Edge Impulse ingestion format, split by directory.
SESSION_LOG.md  Conditions and run-by-run notes for all three sessions.
dataset_report.md  The quality gate output: class balance, dropouts, NaNs, health.

THE SPLIT
---------
Session 3 is the test set and appears in no training window. The split is by SESSION,
not at random: at ~8 Hz consecutive samples are near-duplicates, so a random split
leaks near-identical rows across the boundary and reports memorisation as accuracy.

COLUMNS
-------
t_ms        milliseconds since the run started
dist_mm     ultrasonic distance; -1 means a failed echo (dropped, never interpolated)
d_dist_mm   deviation from the session's saved distance reference
ldr         LDR ADC counts, 0-4095, 10k pulldown
d_ldr       deviation from the session's saved light reference
missed      consecutive failed echoes at this sample
label       0 optimal, 1 too_close, 2 too_far, 3 underlit, 4 overlit
session     1, 2 or 3
pred        model's live on-device prediction, where recorded
infer_us    measured on-device inference time in microseconds, where recorded

The models are trained on the DEVIATION columns, not the absolutes. Each session used a
different physical reference (1308 / 876 / 897 mm), so a model keyed to absolute
positions could not span them - and would break the moment a user saved a new setup.
"""


def add_tree(zf: zipfile.ZipFile, src: Path, arc_root: str,
             skip_dirs: set[str], skip_suffixes: set[str]) -> int:
    n = 0
    for p in sorted(src.rglob("*")):
        if not p.is_file():
            continue
        if any(part in skip_dirs for part in p.parts):
            continue
        if p.suffix in skip_suffixes or p.name == ".gitkeep":
            continue
        zf.write(p, f"{arc_root}/{p.relative_to(src).as_posix()}")
        n += 1
    return n


def verify(path: Path) -> None:
    """Open it back up. The handbook treats a corrupt upload as a non-submission,
    so this is a real check and not a formality."""
    with zipfile.ZipFile(path) as zf:
        bad = zf.testzip()
        if bad is not None:
            sys.exit(f"CORRUPT: {path.name} - first bad entry {bad}")
        n = len(zf.namelist())
    size_mb = path.stat().st_size / 1e6
    print(f"  OK  {path.name}  {n} files, {size_mb:.2f} MB")


def footprint_line() -> str:
    """Read the recorded footprint. Never invent one - a made-up number in a
    submitted README is worse than an honest 'not recorded'."""
    p = ROOT / "reports" / "footprint.json"
    if not p.exists():
        return ("not recorded - run `py -3 tools/record_footprint.py`")
    import json
    fp = json.loads(p.read_text(encoding="utf-8"))
    return (f"{fp['flash_bytes']:,} B flash ({fp['flash_pct']}%), "
            f"{fp['ram_bytes']:,} B RAM ({fp['ram_pct']}%), "
            f"recorded {fp['recorded'][:10]}")


def build_code(ei_url: str) -> Path:
    out = DELIV / f"{STEM}_Code.zip"
    skip = {".git", "__pycache__", "node_modules", ".remember"}
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for sub in ("firmware", "tools", "docs", "reports", "models"):
            add_tree(zf, ROOT / sub, sub, skip, {".pyc"})
        add_tree(zf, ROOT / "data" / "processed", "data/processed", skip, {".pyc"})
        for f in ("README.md", "RUN.md", "AGENTS.md"):
            if (ROOT / f).exists():
                zf.write(ROOT / f, f)
        zf.writestr("README-SUBMISSION.txt", CODE_README.format(
            first=FIRSTNAME, sur=SURNAME, bno=BNUMBER, ei=ei_url,
            footprint=footprint_line()))
        zf.writestr("EDGE_IMPULSE_PROJECT_URL.txt", ei_url + "\n")
    return out


def build_dataset() -> Path:
    out = DELIV / f"{STEM}_Dataset.zip"
    skip = {".git", "__pycache__"}
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        add_tree(zf, ROOT / "data" / "raw", "raw", skip, set())
        add_tree(zf, ROOT / "data" / "processed", "processed", skip, set())
        add_tree(zf, ROOT / "data" / "calibration", "calibration", skip, set())
        # The online trial rows are the raw evidence behind the headline gate G6
        # number. Shipping the report without them asks the marker to take 1.000
        # on trust, and online_trial.py records them precisely so they survive.
        add_tree(zf, ROOT / "data" / "online", "online", skip, set())
        ei = DELIV / "edge_impulse"
        if ei.exists():
            add_tree(zf, ei, "edge_impulse", skip, set())
        rep = ROOT / "reports" / "dataset_report.md"
        if rep.exists():
            zf.write(rep, "dataset_report.md")
        zf.writestr("README-DATASET.txt", DATASET_README.format(
            first=FIRSTNAME, sur=SURNAME, bno=BNUMBER))
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ei-url", default="",
                    help="public Edge Impulse project URL - REQUIRED for a valid submission")
    args = ap.parse_args()

    DELIV.mkdir(parents=True, exist_ok=True)
    ei = args.ei_url.strip()

    if not ei:
        # Not fatal - you may want to test the packaging before the EI project exists -
        # but it must be impossible to ship this by accident without noticing.
        ei = ("!!! MISSING - the Code component is INCOMPLETE without this. "
              "See docs/11-EDGE-IMPULSE-STEPS.md !!!")
        print("\n*** WARNING: no --ei-url given. ***")
        print("*** The handbook requires a link to the public Edge Impulse project")
        print("*** inside the Code zip. Re-run with --ei-url before submitting.\n")

    print("Building...")
    code = build_code(ei)
    data = build_dataset()

    print("\nVerifying (re-opening each archive):")
    verify(code)
    verify(data)

    print(f"\nBuilt in {DELIV}")
    print("\nStill to submit by hand:")
    print(f"  {STEM}_Slides.pptx or .pdf   -> Blackboard")
    print(f"  {STEM}_Video (~1 min)        -> Panopto Media Assignment dropbox, NOT the file dropbox")
    print("\nAfter every upload: screenshot the confirmation into deliverables/receipts/")
    if ei.startswith("!!!"):
        sys.exit(1)


if __name__ == "__main__":
    main()
